### ISSUE TITLE
fabirc 1.16.5 can't update modloader past 0.11.7 and load pack

### ISSUE THREAD

**Issue by superon** [glisco03/things#21]
i'd like to update the modloader to >=0.12.3 as this is a requirement for newer versions of iris.
when i do so as things are i'm seeing this snippet
https://pastebin.com/4ibAPE9Y
apologies for probable lack of important other info

**Comment by gliscowo** [comment]
Could you provide us with the specific modpack/modlist you're running? I have just personally verified again that this launches perfectly fine on its own so I would assume something else than Loader is at blame here
Cheers

**Comment by gliscowo** [comment]
Very cool, buttons are hard

**Comment by superon** [comment]
https://www.curseforge.com/minecraft/modpacks/moancraft/files/3625816

**Comment by gliscowo** [comment]
I'm sorry to close it like this, but this problem is not really fixable on our side. It turns out this is a known compatibility problem with Identity that was I fixed in their newer builds. It still remains in this old version and I doubt they support that anymore. I'll see if I can get a custom build going for you, but for now I'll close this as wontfix
Cheers

**Comment by superon** [comment]
it's fine, no need for custom build for me, i've worked around the issue :)
