### ISSUE TITLE
1.18 Disable apple trinket doesn't work.

### ISSUE THREAD

**Issue by BrokenDawn627** [glisco03/things#23]
version 0.2.12

**Comment by gliscowo** [comment]
What you're seeing here is purely a visual thing - because the trinket slot is registered via data it still shows up. The actual trinket code in the backend is disabled however, as this config option is a relic from when the apple trinket sometimes caused some really strange and hard to diagnose compatibility problem. I'll be releasing a new version soon though, which will also prevent the apple from going in the slot
Cheers

**Comment by BrokenDawn627** [comment]
Thanks. Looking forward to your updates.

**Comment by gliscowo** [comment]
Fixed in 0.2.13
