### ISSUE TITLE
ConcurrentModificationException on coping() Mixin

### ISSUE THREAD

**Issue by spoorn** [glisco03/things#41]
See https://github.com/wisp-forest/owo-lib/issues/29

Things on 1.18.2 also declares a Mixin on OreFeature, but is not thread safe: https://github.com/wisp-forest/things/blob/1.18.2/src/main/java/com/glisco/things/mixin/Copenhagen.java#L25

**Comment by gliscowo** [comment]
This is a known issue fixed in newer builds of owo, sadly that fix never made it into the older Things releases. As 1.18 has reached end of support multiple weeks ago, this will not be fixed anymore
Cheers

**Comment by Bob74** [comment]
@spoorn  It should be fixed for 1.18.2: https://github.com/Bob74/things-1.18.2-fix

I have updated owo-lib to use `Maldenhagen` and set Things to use `owo-lib.Maldenhagen` instead of `Copenhagen`.

You need both:
- [things-0.2.19+1.18.jar](https://github.com/Bob74/things-1.18.2-fix/releases/download/0.2.19%2B1.18/things-0.2.19+1.18.jar)
- [owo-lib-0.7.3+1.18.jar](https://github.com/Bob74/owo-lib-1.18.2-fix/releases/download/0.7.3%2B1.18/owo-lib-0.7.3+1.18.jar)

**Comment by FederAndInk** [comment]
> @spoorn It should be fixed for 1.18.2: https://github.com/Bob74/things-1.18.2-fix
> 
> I have updated owo-lib to use `Maldenhagen` and set Things to use `owo-lib.Maldenhagen` instead of `Copenhagen`.
> 
> You need both:
> 
>     * [things-0.2.19+1.18.jar](https://github.com/Bob74/things-1.18.2-fix/releases/download/0.2.19%2B1.18/things-0.2.19+1.18.jar)
> 
>     * [owo-lib-0.7.3+1.18.jar](https://github.com/Bob74/owo-lib-1.18.2-fix/releases/download/0.7.3%2B1.18/owo-lib-0.7.3+1.18.jar)

Could this be put on curseforge @Bob74 @gliscowo ? in order to make the fix available to modpacks
It would be greatly appreciated :heart:

**Comment by Bob74** [comment]
I've created pull requests if @gliscowo wants to build and upload the fixed versions on CurseForge.
There is not really more I can do :/
