### ISSUE TITLE
[1.20.1] equipping the mining glove crashes game

### ISSUE THREAD

**Issue by temyy** [glisco03/things#71]
[crash-2023-08-12_04.25.31-client.txt](https://github.com/wisp-forest/things/files/12326139/crash-2023-08-12_04.25.31-client.txt)

title, this happens on things 0.3.1+1.20, quilt loader 0.19.2 and it seems to point to artifacts glove renderer but im not sure whether i should submit this issue here or there

**Comment by temyy** [comment]
tested this with all of the artifacts glove trinkets and they worked fine, all of the things gloves crash the game with the same error though

**Comment by BasiqueEvangelist** [comment]
From a cursory reading of the stack trace and source code, the bug seems to be caused by artifacts [not checking whether glove trinkets are from artifacts before applying custom logic.](https://github.com/ochotonida/artifacts/blob/1.20.x/fabric/src/main/java/artifacts/fabric/mixin/client/PlayerRendererMixin.java#L39-L50)
Can you test this with an older artifacts version?

**Comment by BasiqueEvangelist** [comment]
yep, seems to be an artifacts bug
![изображение](https://github.com/wisp-forest/things/assets/72868417/bcbd343c-2046-49df-b626-0a76e7aa3145)

**Comment by BasiqueEvangelist** [comment]
![изображение](https://github.com/wisp-forest/things/assets/72868417/eedd1fdd-4a7e-490d-88e2-b6a4534a5ded)

**Comment by ochotonida** [comment]
Fixed in Artifacts version 9.0.5

**Comment by temyy** [comment]
awesome, thank u both! :)
