### ISSUE TITLE
Crashing when adding a waypoint

### ISSUE THREAD

**Issue by AdrielPalomo9** [glisco03/things#75]
Hello, 
I run a minecraft server with a pretty decent amount of people and my players have been saying the displacement tome crashes players when they tried to type in the text box to add a waypoint. I've tried this myself and it is indeed true but we don't know whats causing it. Does anybody have any input on this?

[crash-2023-09-02_11.36.29-client.txt](https://github.com/wisp-forest/things/files/12504542/crash-2023-09-02_11.36.29-client.txt)

**Comment by gliscowo** [comment]
This problem is caused by an outdated version of owo-lib, upgrading to something like [0.9.3](https://modrinth.com/mod/owo-lib/version/0.9.3+1.19) should help alleviate it. Also, please note that our support period for 1.19.2 has ended a long time ago and we no longer have much of any capacity to investigate issues on those versions

Cheers
