### ISSUE TITLE
[1.18.2] Incompatible with C2ME'S allowThreadedFeatures

### ISSUE THREAD

**Issue by ConqAra** [glisco03/things#76]
Crashes with C2ME (no config changes) enabled upon world generation.
Log: [https://mclo.gs/RKSe7UD](https://mclo.gs/RKSe7UD)
Related: https://github.com/RelativityMC/C2ME-fabric/issues/244

**Comment by Noaaan** [comment]
Could you try this with the `no-cme` build of owo-lib? It is available here: https://www.curseforge.com/minecraft/mc-mods/owo-lib/files/3824297

**Comment by ConqAra** [comment]
Same Result: [https://mclo.gs/K6tV4iy](https://mclo.gs/K6tV4iy)

But due to how many mods I'm using, I will try it without things. I know at least ONE of the issues were things. but let me verify if its only things. could have been fixed with this build but it could be something else.

Edit:
Yeah, no. I removed things and it was completely fine. It's just things causing it. This build didn't solve the issue, I'm afraid.

**Comment by Noaaan** [comment]
Looking through issues and whatnot I realize this issue is related to #51 
Unfortunately we do not support 1.18 anymore, and as such its extremely unlikely an official release will be made. Luckily the related PR did get a release on GitHub, and can be downloaded here: 
https://github.com/Bob74/things-1.18.2-fix/releases

Looking at it you probably need their updated version of owo-lib as well, due to some issues related to sentinel:
https://github.com/Bob74/owo-lib-1.18.2-fix/releases

I have tested these fixes and they do seem to work with C2ME
![image](https://github.com/wisp-forest/things/assets/4163353/5398b2ba-9e22-4822-8e9a-749864570800)

**Comment by ConqAra** [comment]
Works! Thank you
