### ISSUE TITLE
Things mod breaks owo-libs handshake

### ISSUE THREAD

**Issue by Ristovski** [glisco03/things#82]
Reference: https://github.com/wisp-forest/owo-lib/issues/134#issuecomment-1578336874

Can confirm still happens on 1.20.1. Removing `things` fixes the owo-lib handshake failure.

I assume issue is due to related channel code in https://github.com/wisp-forest/things/blob/1.20/src/main/java/com/glisco/things/ThingsNetwork.java

Edit: tested with both `owo-lib-0.11.1+1.20` and `owo-lib-0.11.2+1.20`

**Comment by BasiqueEvangelist** [comment]
You sure it's not just that Things enables owo-handshake, due to it using owo networking stuff?

**Comment by Ristovski** [comment]
Hmm, nice catch, I suppose that might be the case. I will try and bisect if this is caused by some other mod.

**Comment by BasiqueEvangelist** [comment]
In any case, this is probably more because owo-handshake requires network channels to always be present on both the server and the client, even if only the client has the mod (and of course, if the server doesn't do handshaking at all it'll complain too).
If that's the case, the only way to change that behaviour might be to make Things make an optional channel or just manually disable handshake. You could also try to bug glisco into changing handshake behaviour, but I don't really recommend it.

**Comment by Ristovski** [comment]
I have narrowed it down to this on the server, which is not helpful at all:
```
- cloth-config 11.1.106
   \-- cloth-basic-math 0.6.1
- fabric-api 0.90.7+1.20.1 [SNIPPED]
- fabricloader 0.14.24
- java 19
- minecraft 1.20.1
- owo 0.11.2+1.20
   \-- blue_endless_jankson 1.2.2
- things 0.3.1+1.20
   |-- lavender 0.1.0-pre.6+1.20
   |    |-- lavender-md 0.1.0-pre.3+1.20
   |    \-- lavender-md-owo-ui 0.1.0-pre.3+1.20
   \-- reach-entity-attributes 2.3.3-pre.2
- trinkets 3.7.1
   |-- cardinal-components-base 5.2.0
   \-- cardinal-components-entity 5.2.0
```

Running the server with `-Dowo.handshake.disable=true` fixes the issue (obviously). Any ideas?

**Edit**: This is due to a missing client mod. During my testing I removed all client side mods and instead expected/relied on the standard `Received X registry entries that are unknown to this client.` followed by a list of missing mods. owos handshake error screen prevented that one from ever showing up. Ideally, owo would yield to that screen first instead of blocking it (and thus preventing seeing the missing mod entries). Closing as invalid.
