### ISSUE TITLE
Please Fix & The Key IS AWESOME

### ISSUE THREAD

**Issue by Mostovm** [glisco03/things#90]
I like some of the items but there's many issues and good stuff

Receiving effect doesn't go away after removing it
Why no config for items, some I don't want in the game
I thank visuals for items can be turned off
Why use a custom ore, thankfully can be turned off but also should have alternative recipes PLEASE like redstone
Recall Potion shouldnt work and be consumed if theres no spawnpoint. glitchy right there
Displacement thing doesn't really work, couldn't figure it out. I thought it would be a cool thing if it worked
Crafting for scepter and key is perfect
Wax gland is like elytra but for fluid and thats epic
Wax gland should only make you float ontop not inside the fluid

Items that should be mastered and defenitely in the mod are; Recall, Key, Bucket, Ender Pouch, Scepter, Shock Absorber, Item Magnet, Wax Gland, Arm Extender, Placebo, and Fixtures, unique and very helpful especially utilizing the trinket mod.

Everything else I didn't mention shouldn't be in because its a too overpowered but thats my opinion so thats why you should add configurations for those settings because its all about choice

Please listen to this and add configurability thank you. 🙏

**Comment by gliscowo** [comment]
Generally I'd like to remind you that I am not here to take demands - neither are most other modders. As for your troubles, I recommend you consult the Things Almanac once more. It contains detailed instructions on how to use every item in the mod. If you need further assistance, you are always welcome to ask for help in the [Wisp Forest Discord](https://wispforest.io/discord).

As for removing items - since everything in Things is crafted, you can easily remove items from the game by removing their recipe. This is easily achieved with the vanilla datapack system which also lets you adjust recipes to your liking.

Cheers
